language: rust

rust:
  - nightly
  - stable

cache: cargo

addons:
  apt:
    packages:
    - libxxf86vm-dev

script:
  - cargo build --verbose
  - cargo test --verbose

matrix:
    include:
        # Linux builds
        - os: linux
        # OS X builds
        - os: osx
          osx_image: xcode8.1 # OS X 10.12
        - os: osx
          osx_image: xcode7.3 # OS X 10.11
        - os: osx
          osx_image: xcode7.1 # OS X 10.10
        - os: osx
          osx_image: beta-xcode6.2 # OS X 10.9
os:
  - linux
  - osx

after_success: 
  - |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      cargo publish --token ${CRATESIO_TOKEN}
